.TH abiword 1 
.\" NAME should be all caps, SECTION should be 1-8, maybe w/ subsection
.\" other parms are allowed: see man(7), man(1)
.SH NAME
abiword \- WYSIWYG word processor
.SH SYNOPSIS
.B abiword
.RI [option]... 
.RI [file]...
.I ""
.SH "DESCRIPTION"
This manual page documents briefly the
.BR abiword 
command.
This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page.
.PP
.B abiword
is a program that allows the creation of text documents in a pseudo-true
WYSIWYG fasion.

.SH OPTIONS

.TP
.BR \-geometry " geom"
set initial frame geometry

.TP
.BR \-lib " dir"
use dir for application components

.TP
.BR \-nosplash
do not show splash screen


.SH AUTHOR
This manual page was written by Darren Benham <gecko@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
