#!/bin/sh -e

if [ -x /usr/bin/update-menus ] ; then update-menus ; fi

if [ "$1" = "configure" ]; then
	if [ -d /usr/doc -a ! -e /usr/doc/abiword -a -d /usr/share/doc/abiword ]; then
    	ln -sf ../share/doc/abiword /usr/doc/abiword
	fi
fi

