Note that this autoconf build system is less well-tested than the older
build system, and may not work on non-Unix systems yet.

To use the new autoconf build system, take the following steps:

* Unpack the abiword source packages as usual
  You should now have a directory structure like this:
	abi/
	abidistfiles/
	expat/
	psiconv/
	unixfonts/
	wv/
  Not all directories are always needed, but having too many will not do
  any harm.
    
* Build configure and all GNUmakefile.in files
  If you downloaded an official release source package, they should already
  be available; if you checked out the abi tree from CVS, you will have to
  create them yourself.

  You will need to have autoconf (2.13 or newer, 2.50 or newer is best) and
  automake (1.4 or newer, 1.4-p4 or newer is best). Older versions may 
  work, but are untested.

  (Re)build configure and all GNUMakefile.in files with this command:
	cd abi
	./autogen.sh

* Now you can compile this package like any other GNU package:
	cd abi
	./configure [OPTIONS]
	make
	make install [DESTDIR=...]
	
The autogen.sh script runs aclocal, autoheader, automake and autoconf. You
should re-run it whenever you make any changes to a Makefile.am or to
configure.in. 

Because configure.in scripts for autoconf version 2.13 and version 2.50 are
not quite compatible, I included two versions of it. At this moment,
autogen.sh will automatically select the right one for you. Note that you
should still upgrade to autoconf 2.50, because this is only a temporary
arrangement.

When we create a source distribution, we should always include the files
generated by a run of autogen.sh. Once that is done, our users will not
need to have autoconf and automake installed.

  Frodo Looijaard <frodol@dds.nl>

===========================================================================

Well, Jesper asked for this at GUADEC, so here it is.  The following
tarball contains the entire abiword tree, but none of the peer
directories, since they haven't been changed.  Here's how I would
reccomend playing with it:

  $ wget http://abisource.com/~sam/abi-auto.tar.gz
  $ mkdir abi-auto
  $ cd abi-auto
  $ tar -xzvf ../abi-auto.tar.gz
  $ ln -s ../wv wv
  $ ln -s ../psiconv psiconv
  $ ln -s ../expat expat
  $ pwd
  abi-auto
  $ ls
  abi expat psiconv wv
  $ cd abi
  $ ./autogen.sh [ this runs automake and autoconf ]  
  $ cd ..
  $ mkdir build
  $ cd build
  $ ../abi/configure
  $ make

When you're done, the binaries, called AbiWord_d and AbiWord_s, will
be located in abi/src/wp/main/unix/.  They should be directly runnable.  

Currently, no options to configure are supported.  I should have
--with-gnome and --with-debug done soon, though.

Tools required:
  autoconf (requires GNU m4)
  automake (requires perl)

Again, the tarball is at http://abisource.com/~sam/abi-auto.tar.gz

Have fun, and feel free to ask questions, or tell me how badly I
implemented this.  :-)
           
sam th --- sam@uchicago.edu --- http://www.abisource.com/~sam/
OpenPGP Key: CABD33FC --- http://samth.dyndns.org/key
DeCSS: http://samth.dyndns.org/decss

