
presentation_pkgs="$glib_req"

PRESENTATION_CFLAGS=
PRESENTATION_LIBS=

if test "$enable_presentation" == "yes"; then

PKG_CHECK_MODULES(PRESENTATION,[ $presentation_pkgs ])

PRESENTATION_CFLAGS="$PRESENTATION_CFLAGS"'${WP_CPPFLAGS}'
PRESENTATION_LIBS="$PRESENTATION_LIBS"'${PLUGIN_LIBS}'

fi

AC_SUBST([PRESENTATION_CFLAGS])
AC_SUBST([PRESENTATION_LIBS])

