
opendocument_pkgs="$gsf_req"

OPENDOCUMENT_CFLAGS=
OPENDOCUMENT_LIBS=

if test "$enable_opendocument" == "yes"; then

PKG_CHECK_MODULES(OPENDOCUMENT,[ $opendocument_pkgs ])

OPENDOCUMENT_CFLAGS="$OPENDOCUMENT_CFLAGS"'${WP_CPPFLAGS}'
OPENDOCUMENT_LIBS="$OPENDOCUMENT_LIBS"'${PLUGIN_LIBS}'

fi

AC_SUBST([OPENDOCUMENT_CFLAGS])
AC_SUBST([OPENDOCUMENT_LIBS])

