
olpctoolbar_pkgs="$gtk_req"

OLPCTOOLBAR_CFLAGS=
OLPCTOOLBAR_LIBS=

if test "$enable_olpctoolbar" == "yes"; then

PKG_CHECK_MODULES(OLPCTOOLBAR,[ $olpctoolbar_pkgs ])

OLPCTOOLBAR_CFLAGS="$OLPCTOOLBAR_CFLAGS "'${WP_CPPFLAGS}'
OLPCTOOLBAR_LIBS="$OLPCTOOLBAR_LIBS "'${PLUGIN_LIBS}'

fi

AC_SUBST([OLPCTOOLBAR_CFLAGS])
AC_SUBST([OLPCTOOLBAR_LIBS])

