
loadbindings_pkgs="$glib_req"

LOADBINDINGS_CFLAGS=
LOADBINDINGS_LIBS=

if test "$enable_loadbindings" == "yes"; then

PKG_CHECK_MODULES(LOADBINDINGS,[ $loadbindings_pkgs ])

LOADBINDINGS_CFLAGS="$LOADBINDINGS_CFLAGS"'${WP_CPPFLAGS}'
LOADBINDINGS_LIBS="$LOADBINDINGS_LIBS"'${PLUGIN_LIBS}'

fi

AC_SUBST([LOADBINDINGS_CFLAGS])
AC_SUBST([LOADBINDINGS_LIBS])

